# Generated by Django 2.1.7 on 2019-03-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fileIdentifier',
            fields=[
                ('uniqueIdentifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('breaktime', models.IntegerField()),
                ('Identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShiftsByIdentifier', to='roastersite.fileIdentifier')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeByIdentifier', to='roastersite.fileIdentifier'),
        ),
    ]
