# Generated by Django 2.1.7 on 2019-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roastersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
